# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7

    steps:
      - checkout

      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install

      - run:
          name: Pull LFS Files
          command: git lfs pull

      - run:
          name: Install Shellcheck
          command: |
            curl -OL https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
            tar xf shellcheck-stable.linux.x86_64.tar.xz
            sudo mv shellcheck-stable/shellcheck /usr/local/bin
          working_directory: /tmp/shellcheck

      - restore_cache:
          keys:
          - cache-{{ checksum "env_pytorch.yml" }}

      - run:
          name: install dependencies
          command: |
            if [[ ! -d "$HOME/miniconda" ]]; then
              curl -OL https://repo.continuum.io/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh
              bash Miniconda3-4.7.10-Linux-x86_64.sh -b -p "$HOME/miniconda";
              source "$HOME/miniconda/etc/profile.d/conda.sh"
              sudo pip install --upgrade pip
              # conda update conda
              conda env create -f env_pytorch.yml
            else
              echo "Using cached miniconda";
            fi
           

      - save_cache:
          key: cache-{{ checksum "env_pytorch.yml" }}
          paths:
            - "$HOME/miniconda"

      - run:
          name: run prediction tests
          when: always
          command: |
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            conda activate py36pytorch
            cd core && PYTHONPATH=. python -m pytest -s text_recognizer/tests/*

      - run:
          name: run evaluation tests
          command: |
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            conda activate py36pytorch
            cd core && PYTHONPATH=. python -m pytest -s evaluation/*

      - store_artifacts:
          path: test-reports
          destination: test-reports
